version: '3.8'

services:
  youtube-resolver:
    build: .
    container_name: youtube-resolver
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      # Mount cookies directory as writable persistent store for yt-dlp
      - ./cookies:/data/cookies
      - ./logs:/app/logs
