version: '3.8'

services:
  # YouTube Resolver (servidor local)
  youtube-resolver:
    build: 
      context: ./youtube-resolver
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Volume para cookies persistentes
      - ./cookies:/data/cookies:ro
      - ./youtube-resolver/logs:/app/logs
    environment:
      - NODE_ENV=development
      - YTDLP_COOKIES_PATH=/data/cookies/cookies.txt
      # Security (optional)
      # - ALLOWED_ORIGINS=http://localhost:3000
      # - ALLOWED_DEST_SCHEMES=https
      # - ALLOWED_DEST_HOST_SUFFIXES=googlevideo.com
      # - ALLOWED_DEST_CIDRS=173.194.0.0/16,74.125.0.0/16
    networks:
      - musa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Discord Bot (usando o resolver local)
  musa-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      youtube-resolver:
        condition: service_healthy
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RESOLVER_URL=http://youtube-resolver:3001
      - NODE_ENV=development
    volumes:
      - ./logs:/app/logs
    networks:
      - musa-network
    restart: unless-stopped

networks:
  musa-network:
    driver: bridge
