version: '3.8'

services:
  musa-bot:
    build: .
    container_name: musa-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
